### PR TITLE
Rename files to better match with the content

### PR DESCRIPTION
**Pull request by ericrommel**

### CODE REVIEW

**Review by SSN-SPB — APPROVED** [review]

**Review by SSN-SPB — CHANGES_REQUESTED** [review]
removing 'week' from file_name is a perfect idea.
What about removing 'week' from the folder name as well and name it as (e.g.) topic01/topic02/etc

**Comment by ericrommel** [comment]
> removing 'week' from file_name is a perfect idea. What about removing 'week' from the folder name as well and name it as (e.g.) topic01/topic02/etc

This is done. Please check it again.

**Review by ksauhen — APPROVED** [review]

**Review by SSN-SPB — DISMISSED** [review]

**Review by ksauhen — APPROVED** [review]

**Review by ksauhen — APPROVED** [review]

**Review by SSN-SPB — DISMISSED** [review]
Time to merge.

**Review by ksauhen — APPROVED** [review]

**Review by SSN-SPB — APPROVED** [review]
Time to merge

**Pull request merged**
